### ISSUE TITLE
Cannot Complete Raw Gold and Silver Ore Line Quest

### ISSUE THREAD

**Issue by GlintingPlanet11** [NyagiByte/Compression#14]
To Complete the Quest you need Raw Silver from Immersive Engineering which does not drop when breaking Silver Ore in boulders. Instead the Silver Ore drops Raw Silver from Thermal Series.

**Comment by GlintingPlanet11** [comment]
Same Problem with the Raw Nickel Quest

**Comment by GlintingPlanet11** [comment]
Lead and Uranium also have the same problem

**Comment by NyagiByte** [comment]
can you describe which ores drop for the nickel/lead/uranium quests

**Comment by GlintingPlanet11** [comment]
For Uranium:
Ore That spawns in boulders is from the Nuclearcraft Neoteric Mod
Drops Uranium Chunk from the same mod
For Quest you need Mekanism Raw Uranium

For Nickel:
Ore That Spawns in Bouldersf is from the mod Thermal Series
Drops Raw Nickel from the same mod
For the Quest you need Raw Nickel from Immersive Engineering

For Lead:
Ore that spawns in boulders is from Thermal Series
Drops Raw Lead from the same mode
For Quest you need Raw Lead from Immersive Engineering

On another note the /locate structure compstruct:[material]_boulder does not seem to work properly

**Comment by NyagiByte** [comment]
Fixed on master!
