### ISSUE TITLE
Grass (the instant break) drops seeds far too often

### ISSUE THREAD

**Issue by coraqualia** [NyagiByte/Compression#15]
Typical grass has a 12.5% chance of dropping just wheat seeds when broken in vanilla minecraft. However, in loottables.js five more rolls are added for five different seeds. This means that generally, breaking grass drops seeds 32.3% of the time at least - not including the chances for stuff like IE hemp seeds, which aren't incorporated. Empirically over a few thousand grass breaks, I got that it drops seeds 50% of the time. However, this is unimportant compared to the likelihood of how it clutters inventory; breaking only 20 grass, it filled up 6 slots 94% +- 1.2 of the time, and breaking only 10 grass at a time it filled up 3 or more slots in all but 4.8% of cases. 10 grass can easily be broken in under a second, and 64% of the time immediately filled up four inventory slots.
My math might be bad, but regardless; the GTFO option may be superior in just having it drop general seeds you can craft into the desired seeds otherwise, or otherwise "sort" through a mixed seed to get a specific seed.

**Comment by NyagiByte** [comment]
I do quite like the mixed seeds idea, i'll consider adding that in as part of nb&b

**Comment by Killerqu00** [comment]
Hear me out - seed pouches

**Comment by NyagiByte** [comment]
> Hear me out - seed pouches

eh that just ends up being another thing taking up inventory space

with mixed seeds you can just toss them out if they enter your inventory, plus it opens up automating grass breaking to get mixed seeds for other recipes

**Comment by Killerqu00** [comment]
> > Hear me out - seed pouches
> 
> eh that just ends up being another thing taking up inventory space
> 
> with mixed seeds you can just toss them out if they enter your inventory, plus it opens up automating grass breaking to get mixed seeds for other recipes

fair

**Comment by NyagiByte** [comment]
![Screenshot 2024-04-24 201641](https://github.com/NyagiByte/Compression/assets/124478839/7622cb91-a564-497e-aa21-7cdc9fa4e92a)
Gonna go into master for 0.20 👍

**Comment by NyagiByte** [comment]
Cant get loottables to work
