### ISSUE TITLE
Suggestion: Give Copper Backtanks the ability to be put on the Curious Back Slot

### ISSUE THREAD

**Issue by GlintingPlanet11** [NyagiByte/Compression#21]
In the Curious Invetory there is a slot for "Back", my suggestion would be to give the Copper Backtank from Create the ability to be put into that slot, so that you can were armor and the copper backtank at the same time.

**Comment by Killerqu00** [comment]
that should probably be a suggestion for Create, because it is a mod compatibility thing

**Comment by GlintingPlanet11** [comment]
Can't you just use the example Datapack provided from Curious API and add create:copper_backtank to a back.json file you create?

**Comment by Killerqu00** [comment]
> Can't you just use the example Datapack provided from Curious API and add create:copper_backtank to a back.json file you create?
> 

that might work, but there is a possibility that it won't identify backtank as equipped one in that case

**Comment by GlintingPlanet11** [comment]
Tested it, when having it equipped in the back slot an extendo grip won't lose durability.
![image](https://github.com/NyagiByte/Compression/assets/166944932/2ee97b7b-45d2-4dd2-ab94-4738ce7c85b2)
![image](https://github.com/NyagiByte/Compression/assets/166944932/3245e77b-7689-43c5-b90d-92b16b77287e)
