### ISSUE TITLE
Torn wool ball recipe overridden by string

### ISSUE THREAD

**Issue by RobustTadpole66** [NyagiByte/Compression#28]
The torn wool ball recipe is overridden by a recipe for string. Due to the mill not being filterable, this is not able to be fixed unless the string recipe is removed, or the torn wool ball recipe is changed.

**Comment by GlintingPlanet11** [comment]
Already fixed, pls check for your Issue first before reporting it.

**Comment by NyagiByte** [comment]
already fixed on master

**Comment by NyagiByte** [comment]
dup

**Comment by RobustTadpole66** [comment]
Oh, sorry. New to github and didn't know
