### ISSUE TITLE
[Load My F***ing tags] Error Message when opening a world

### ISSUE THREAD

**Issue by GlintingPlanet11** [NyagiByte/Compression#36]
When Opening a world this message pop-ups in chat:
![image](https://github.com/user-attachments/assets/815daf95-27ea-4b6f-972f-f42f65b80abb)

Logs:
[latest.log](https://github.com/user-attachments/files/16514832/latest.log)

**Comment by NyagiByte** [comment]
this is known, will probably remove the mod on release
