### ISSUE TITLE
Pen assembly not working

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#38]
._.

https://github.com/user-attachments/assets/ec201f4b-6450-45aa-8cee-6aeb4ae3677e

**Comment by ummpasta** [comment]
<img width="786" alt="image" src="https://github.com/user-attachments/assets/b07a5dad-62cf-49b7-828d-87092f55cdf0">
This recipe only take screate iron sheets but not the chem lib iron plate

**Comment by NyagiByte** [comment]
fixed on master
