### ISSUE TITLE
Belt Grinder Crash

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#39]
https://github.com/user-attachments/assets/5cfaf542-b501-4c1d-bd06-f88016ca9375

**Comment by ummpasta** [comment]
World also crashes on startup after this.

**Comment by NyagiByte** [comment]
huh, send over the crash logs

**Comment by ummpasta** [comment]
[latest.log](https://github.com/user-attachments/files/16569887/latest.log)

**Comment by ummpasta** [comment]
[crash-2024-08-10_20.03.43-server.txt](https://github.com/user-attachments/files/16569889/crash-2024-08-10_20.03.43-server.txt)

**Comment by BigBarza** [comment]
The root cause has been identified, discussing fixes.

**Comment by ummpasta** [comment]
Same bug occurs when you use the string coiling machines

**Comment by ummpasta** [comment]
HAHAHAHHAHAHAHAH the lathe crashes when the ponder tries to place the item in the lathe

https://github.com/user-attachments/assets/5b4447a0-db30-4638-a0d1-3e84dacc3063
