### ISSUE TITLE
quartz fiber cannot be x4

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#40]
![Screenshot 2024-08-14 115718](https://github.com/user-attachments/assets/b00be419-9be3-4643-a38a-525e98b6e644)

**Comment by ummpasta** [comment]
<img width="426" alt="image" src="https://github.com/user-attachments/assets/135d8327-eba8-43d3-81ff-89ad715955ad">
![Screenshot 2024-08-14 123039](https://github.com/user-attachments/assets/97440d9b-96c8-49c9-a00e-89b5773c8aeb)
Ore quests have both thermal and immersive raw ores XD

**Comment by ummpasta** [comment]
![Screenshot 2024-08-14 123039](https://github.com/user-attachments/assets/b0d69e22-3c74-4797-a4b3-b2fb657f0c47)

**Comment by NyagiByte** [comment]
fixed!
