### ISSUE TITLE
Vibration Chamber Power Bug

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#41]
<img width="362" alt="image" src="https://github.com/user-attachments/assets/a7878d8b-02c8-45ec-99f5-b1edf3407681">
<img width="347" alt="image" src="https://github.com/user-attachments/assets/6e0e4177-72c8-4dce-8ba9-538b945af9e2">

When my Ae2 System is full of power the Vibration Chamber gives 400ae but when its empty its 40ae

I think the configs are misconfigured as its max and min seems like it should be reversed

<img width="712" alt="image" src="https://github.com/user-attachments/assets/34945059-7dd9-4e03-891b-5c43dc60541a">

Also x4 channels when xd

**Comment by ummpasta** [comment]
<img width="322" alt="image" src="https://github.com/user-attachments/assets/e405da63-1626-4f9c-b6c7-70137764f61d">

**Comment by NyagiByte** [comment]
what the hell lol

**Comment by NyagiByte** [comment]
fixed
