### ISSUE TITLE
Yeast Culture Bucket

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#42]
In-world Crafting of the yeast culture bucket only works if you separate the 2 different sugars.
https://github.com/user-attachments/assets/0ce761e9-d466-4c7c-8c73-63dacfeb4b98
I suggest making a quest telling people how or reworking the recipe

**Comment by ummpasta** [comment]
https://github.com/user-attachments/assets/78800c23-078e-407d-a896-f31f1ecffb87

**Comment by ummpasta** [comment]
Bottle of vinegar craft returns 2 buckets

https://github.com/user-attachments/assets/8bdcbaae-c686-4535-839d-71ae1a8a8773

**Comment by NyagiByte** [comment]
Fixed!
