### ISSUE TITLE
Blueprint Crash

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#43]
Removing the crafting components blueprint from the Engineering workbench crashes the game

https://github.com/user-attachments/assets/37208e87-e0d1-48af-a922-2cdbefecf17e

**Comment by ummpasta** [comment]
[crash-2024-08-28_19.28.18-client.txt](https://github.com/user-attachments/files/16782646/crash-2024-08-28_19.28.18-client.txt)

**Comment by ummpasta** [comment]
[latest.log](https://github.com/user-attachments/files/16782654/latest.log)

**Comment by ummpasta** [comment]
Currently the the kinetic dynamo and thermoelectric generator need the dissolver to be crafted is that gonna be changed eventually?

**Comment by NyagiByte** [comment]
> Currently the the kinetic dynamo and thermoelectric generator need the dissolver to be crafted is that gonna be changed eventually?

This is intended

**Comment by NyagiByte** [comment]
> Removing the crafting components blueprint from the Engineering workbench crashes the game
> 2024-08-28.19-27-58.mp4

i'm not sure this is fixable sadly

**Comment by BigBarza** [comment]
We've identified the cause, will push an update to Compressed Engineering to patch this issue.
