### ISSUE TITLE
Alchemistry Assembly Bug

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#44]
https://github.com/user-attachments/assets/562d73ea-51f5-46a5-b453-91c94bd9c7cc

Trying to craft atomizer also just crafts a liquefier, only dissolver and liquefier recipes work.

**Comment by NyagiByte** [comment]
Turns out this was an issue with similar transitional items! I have temp fixed it but will have proper traditional items next time i update nb&b
