### ISSUE TITLE
Uncraftables

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#48]
<img width="116" alt="image" src="https://github.com/user-attachments/assets/a1354cc4-ecc6-4df7-8e4b-2886c87a5f5f">

These new custom steel blocks have no recipes

<img width="308" alt="image" src="https://github.com/user-attachments/assets/c0696a89-e0e3-439b-a2fd-fcd2b46271f3">

Unable to craft Redstone engineering block as there is only 6 slots.

**Comment by NyagiByte** [comment]
Fixed on master! Ty
