### ISSUE TITLE
XD yall forgot to remove a backpack recipe

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#51]
<img width="302" alt="image" src="https://github.com/user-attachments/assets/e3ededc0-7b43-4220-ae5d-03581e893bdf">

Its the copper backpack surrounded by 4 iron

**Comment by ummpasta** [comment]
![image](https://github.com/user-attachments/assets/6fe08a2c-66fa-4681-b2c3-9b5e897561bf)

Also the inworld transformation of yeast bucket disappeared?

**Comment by ummpasta** [comment]
also the backpack doesnt keep the item/upgrade inside it after upgrading

**Comment by NyagiByte** [comment]
Backpacks fixed on master
