### ISSUE TITLE
Chem lib uranium block doesnt work with the Thermoelectric generator

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#53]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/3edfef61-4051-4610-8f6a-773af3dc184a">

<img width="656" alt="image" src="https://github.com/user-attachments/assets/ed3b00b3-38d6-4f27-a528-8d7bbcc10bff">

**Comment by NyagiByte** [comment]
This is intentional as uranium as a heat source doesn't make a huge amount of sense. RTG's will play a role with thermopiles later on
