### ISSUE TITLE
Metal press issues

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#56]
Metal press requires the mana steel lattice as the curving press needs a runic altar to be made

**Comment by ummpasta** [comment]
Also forming the metal press is a little buggy and weird.


https://github.com/user-attachments/assets/7bf35ef9-7ce5-4a80-8378-661dae0ce1c9



It only forms on 1 side and will not form if you click the hammer on the wrong side of the machine is the proby because the original piston had to be placed downwards and would not form on any other side.

<img width="293" alt="image" src="https://github.com/user-attachments/assets/60ccb40d-efe9-4433-8d88-ab8c30ad577b">

Also proby need to change some text in the manual

**Comment by ummpasta** [comment]
Im unable to form the Fermenter

https://github.com/user-attachments/assets/2d35ddb3-3e68-469f-8b54-4da428e51a49

**Comment by RobustTadpole66** [comment]
Don't know how to fix the first one but the fermenter forms now.

**Comment by NyagiByte** [comment]
> Don't know how to fix the first one but the fermenter forms now.

I will adjust the recipe of the curving press

**Comment by RobustTadpole66** [comment]
Oh also I said it in the discord but not here, but, we cannot change the text in the manual, nor can we make the metal press not sided to form.

**Comment by NyagiByte** [comment]
recipe has been changed, softlock fixed
