### ISSUE TITLE
Supplementaries Bed recipe

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#57]
<img width="339" alt="image" src="https://github.com/user-attachments/assets/37727b6f-e282-4e2f-a753-6b22cc82a2e2">

It uses feather block to make the bed

![image](https://github.com/user-attachments/assets/185e072c-571e-4e09-a20b-0933b84b40f0)

Proficiency tab's immersive assembly set to autodetect instead of submit

**Comment by NyagiByte** [comment]
good catch, will fix during next batch of changes

**Comment by NyagiByte** [comment]
fixed on master
