### ISSUE TITLE
Duplicate paper recipes

### ISSUE THREAD

**Issue by Killerqu00** [NyagiByte/Compression#6]
reported by Sammy on discord; there are 2 recipes for bark->paper with different yields, 2x paper recipe is redundant

![image](https://github.com/NyagiByte/Compression/assets/47712032/6d141452-5b7f-46de-8e46-3c1803841ca1)
![image](https://github.com/NyagiByte/Compression/assets/47712032/c14d18a9-20b2-482a-82e7-8be21e819045)

**Comment by NyagiByte** [comment]
Fixed
