### ISSUE TITLE
Chemlib items have no model when in the hotbar

### ISSUE THREAD

**Issue by GlintingPlanet11** [NyagiByte/Compression#61]
Notably I did not check all items, just Iron and Gold Plates aswell as the first items from the mod in EMI. 
![image](https://github.com/user-attachments/assets/7671631b-d0b0-4478-ac5d-45631062ab7a)
![image](https://github.com/user-attachments/assets/8c3da6cd-2017-4323-b37f-138125f97e20)

Maybe this should be a different post, but I would like to say that I liked the Create / Thermal Textures for plates more then texture now.
Of course you may disagree with this but just wanted to say it.

**Comment by NyagiByte** [comment]
This is a known issue tho i'm not sure what is causing it. As for the textures JJ is already working on a resource pack to re-texture the chemlib stuff

**Comment by BigBarza** [comment]
Tracked down the issue to ImmediatelyFast. Changed a config that should make the items reappear.
https://github.com/NyagiByte/Compression/commit/97193fb5a3133f5efa0609943c5e177bb525a195
