### ISSUE TITLE
Box of Carrots conflict makes it hard to make diammonium phosphate

### ISSUE THREAD

**Issue by m4n02** [NyagiByte/Compression#72]
![image](https://github.com/user-attachments/assets/43f09362-2408-4ed0-a8de-f7ff4f16b9be)
Instead of farmer's delight, you get thermal series, which cannot be processed into diammonium phosphate

**Comment by m4n02** [comment]
![image](https://github.com/user-attachments/assets/9cac73d4-51dc-4b21-bc27-f8076cbd9278)
Same issue with potato crates, but this time it's Quark

**Comment by NyagiByte** [comment]
fixed on master
