### ISSUE TITLE
[Mod Request]: Drawers/Functional Storage

### ISSUE THREAD

**Issue by antrobot1234** [NyagiByte/Compression#74]
I'm a bit surprised that this modpack does not provide any drawer mod. I suggest adding it as having voiding functionality is critical for farms that produce byproducts (e.g. washing gravel -> flint, tree farms giving excess saplings/sticks, crop farms giving excess seeds, etc.). Also, The convenience of having access to certain critical resources without needing to open a GUI is appreciated. Either mod would be fine, as they are practically interchangeable functionality-wise.

**Comment by NyagiByte** [comment]
So the lack of drawers mod was actually intentional as i felt far too many expert packs use them and they tend to be somewhat boring. Instead we have the [Packages Mod](https://www.curseforge.com/minecraft/mc-mods/packages) since they offer more interesting solutions to dense storage

**Comment by antrobot1234** [comment]
How do you handle voiding excess from a farm then?

**Comment by NyagiByte** [comment]
That would be up to the player to decide how it is handled
