### ISSUE TITLE
Tough Bag Recipe Sequence Mishaps

### ISSUE THREAD

**Issue by m4n02** [NyagiByte/Compression#76]
While making the Soil Conditioner, when you reach 4/8 progress, deploying yet another bone meal to the tough bag magically converts it to the Mystic Fertilizer on 5/8 progress.
![image](https://github.com/user-attachments/assets/299a1dab-58b4-4ca3-bf13-c8dbea09affd)

**Comment by NyagiByte** [comment]
fixed on master, half the price now too!
