### ISSUE TITLE
Create Stress values are still default

### ISSUE THREAD

**Issue by ummpasta** [NyagiByte/Compression#78]
https://create.fandom.com/wiki/Water_Wheel
256 su is the default stress capacity
https://create.fandom.com/wiki/Windmill
8192 is max default stress capacity
https://create.fandom.com/wiki/Steam_Engine
16,384 su is the default stress capacity

You added the file to the defaultconfig but its placed wrong
https://github.com/NyagiByte/Compression/commit/d7856ce143c1536dd391f5314f40d6c204f0bf86
supposed to be defaultconfigs/create-server.toml
not defaultconfigs/serverconfig/create-server.toml

Also windmill should be 16384 if everything is doubled
https://discord.com/channels/957759022965067808/1124850735209795654/1233430362634453093

			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v2.capacity]
				copper_valve_handle = 8.0
				hand_crank = 256.0
				steam_engine = 65536.0
				creative_motor = 16384.0
				large_water_wheel = 2048.0
				water_wheel = 512.0
				windmill_bearing = 8192.0

**Comment by ummpasta** [comment]
The stress units are x4 ingame compared to the config btw
		#[in Stress Units]
		#Configure how much stress a source can accommodate for.
		[kinetics.stressValues.v2.capacity]
		
![image](https://github.com/user-attachments/assets/b6f3a29b-ecf5-40d3-a034-f38e75b5eaa3)

**Comment by NyagiByte** [comment]
fixed on master (hopefully)
