### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Tralomine** [NyagiByte/Compression#8]
crash on startup, Linux x64, java 17, compression 0.1.7 installed via prismlauncher,  AMD Ryzen 7 7840U, 

[crash-2024-04-11_23.27.05-client.txt](https://github.com/NyagiByte/Compression/files/14955442/crash-2024-04-11_23.27.05-client.txt)

**Comment by Killerqu00** [comment]
Seems like your game fails to detect/install GLFW library..?
Try to select the instance -> Edit -> Settings -> Workarounds -> Use system installation of GLFW and change it from whatever it is currently

**Comment by Tralomine** [comment]
![image](https://github.com/NyagiByte/Compression/assets/11725390/0cba60fe-1acc-4f06-b693-216035fda10b)
okay that's new...

[crash-2024-04-13_12.19.15-client.txt](https://github.com/NyagiByte/Compression/files/14967055/crash-2024-04-13_12.19.15-client.txt)

**Comment by Tralomine** [comment]
(it's weird tho because my other instances work fine without doing anything)

**Comment by Tralomine** [comment]
(okay it fails even with glfw-wayland-minecraft 
[crash-2024-04-13_12.23.35-client.txt](https://github.com/NyagiByte/Compression/files/14967062/crash-2024-04-13_12.23.35-client.txt)
)

**Comment by Killerqu00** [comment]
> (it's weird tho because my other instances work fine without doing anything)

perhaps we have a mod that changes app icon and does not have compatibility with wayland

i will probably do some testing on this later, not working on wayland is not very good

**Comment by Tralomine** [comment]
which mod would it be? I can try to see if disabling it works

**Comment by Killerqu00** [comment]
> which mod would it be? I can try to see if disabling it works

no idea, I thought we had no mods for menu customization yet...
you use Arch with Wayland, right? I can try to reproduce

**Comment by Tralomine** [comment]
okay it was just my version of glfw-wayland-minecraft that was outdated (the default AUR version), I updated it and now it launches fine
